### ISSUE TITLE
Patatap Clone

### ISSUE THREAD

**Issue by siya-pathak** [RajVarsani/html-archives#1]
Hey! I'd love to make a Patatap Clone project, please consider assigning me to this. Thank you!

**Comment by RajVarsani** [comment]
Sure, Go ahead,
Make sure to read [CONTRIBUTING.md](https://github.com/RajVarsani/html-archives/blob/main/CONTRIBUTING.md) before starting contributions.
Best of luck!

**Comment by RajVarsani** [comment]
@siya-pathak Any update so far?
