### ISSUE TITLE
Bug:  Fix typo's in the readme file

### ISSUE THREAD

**Issue by thisShouldNotBeWorking** [RajVarsani/html-archives#10]
### What happened?

There are some typing errors in the readme file that need to be fixed

### How can we reproduce this bug?

You can open the readme file and check for the typo's

### Additional context (if any)

![image](https://user-images.githubusercontent.com/82517773/193880970-d427a806-3108-4c35-8527-e5ad573a9bf3.png)
branch spelling is wrong

![image](https://user-images.githubusercontent.com/82517773/193881074-0499a140-6c31-477c-b568-cbf3a2b16717.png)
"m your code" is a typo

![image](https://user-images.githubusercontent.com/82517773/193881236-6be083b5-75f9-4873-86de-52af236d3313.png)
it should be that's it

**Comment by RajVarsani** [comment]
Sure, Go ahead!
