### ISSUE TITLE
Title: Ping Pong game

### ISSUE THREAD

**Issue by mridulpal019** [RajVarsani/html-archives#119]
### Describe your issue.

Want to add a Ping pong game using basic js ,css and html

**Comment by rajnish254** [comment]
kindly Assign me that issue
Thanks

**Comment by RajVarsani** [comment]
Sure @mridulpal019

**Comment by mridulpal019** [comment]
@RajVarsani i want to contribute to this issue. ..that's why i raised it..!!

**Comment by RajVarsani** [comment]
Cool, you both may add your own versions. 

Happy hacking 🙌
