### ISSUE TITLE
Title: carousel

### ISSUE THREAD

**Issue by shivang1919** [RajVarsani/html-archives#140]
### Describe your issue.

consisting of a carousel of sceneric images

**Comment by RajVarsani** [comment]
Sure go ahead @shivang1919 🙌

**Comment by RajVarsani** [comment]
Any update @shivang1919 ?

**Comment by shivang1919** [comment]
I did a pr actually you may check rotating carousel

**Comment by RajVarsani** [comment]
The issue wasn't mentioned there.
Cool nw. 
Just make sure you add issue references in future PRs.
