### ISSUE TITLE
Adding a preloader to the Web Page

### ISSUE THREAD

**Issue by YashBawa** [RajVarsani/html-archives#3]
### Is your feature request related to a problem? Please describe.

A preloader makes the website look even better while opening it. 
This feature is not related to any problem , its just an additional styling to make the website look better. 

### Describe the solution you'd like.

The preloader would be visible each time the web page is opened in the browser or reloaded. 
A little bit improvisation in HTML and CSS files would work well for adding this feature.

### Additional context (if any)

@RajVarsani please assign me this issue under hacktoberfest label, As I want to add this feature to the website.
Thank You

**Comment by RajVarsani** [comment]
Sure, Go ahead,
Make sure to read [CONTRIBUTING.md](https://github.com/RajVarsani/html-archives/blob/main/CONTRIBUTING.md) before starting contributions.
Best of luck!

**Comment by YashBawa** [comment]
Yaa sure , would follow the guidelines and start working on it.
Please add the hacktoberfest label .
Thanks
