### ISSUE TITLE
Title: A profile card

### ISSUE THREAD

**Issue by SanDiego2049** [RajVarsani/html-archives#50]
### Describe your issue.

I have an animated profile card template that can easily be reused in different scenarios.

### Screenshots (if applicable).

![Screenshot (126)](https://user-images.githubusercontent.com/82504136/194082239-7d3723c1-362b-4182-b4eb-1de063c72c2d.png)

**Comment by RajVarsani** [comment]
Sure LGTM. You may go ahead and add it to the repo.
Best of luck
