### ISSUE TITLE
Title: Adding Tic-Tac-Toe Game

### ISSUE THREAD

**Issue by AK-codingmaniac** [RajVarsani/html-archives#65]
### Describe your issue.

Hey, I want to add the Tic-Tac-Toe game in the repo
Please consider assigning me to this
Thank you!

**Comment by RajVarsani** [comment]
Sure @AK-codingmaniac, Go ahead 
Make sure to follow contribution guide lines.
Best of luck.

**Comment by AK-codingmaniac** [comment]
@RajVarsani I have published PR #71 regarding the above issue 
Please see to it
