### ISSUE TITLE
Title: Elon Musk Tribute Page 

### ISSUE THREAD

**Issue by anshulsoni4** [RajVarsani/html-archives#8]
### Describe your issue.

I will make a tribute web page, which will be fully responsible. Tribute to the great Elon Musk

**Comment by RajVarsani** [comment]
Sure, Go ahead,
Make sure to read [CONTRIBUTING.md](https://github.com/RajVarsani/html-archives/blob/main/CONTRIBUTING.md) before starting contributions.
Best of luck!

**Comment by anshulsoni4** [comment]
sure @RajVarsani

**Comment by RajVarsani** [comment]
Yes, @legit-develop. it is still Open
You may contribute if you want to.

**Comment by RajVarsani** [comment]
@anshulsoni4 are you working on the issue, or do you want me to assign it to @legit-develop?

**Comment by anshulsoni4** [comment]
@RajVarsani you can assign this to someone

**Comment by RajVarsani** [comment]
Okay, I'm assigning this to @legit-develop

**Comment by RajVarsani** [comment]
Any update @legit-develop?
