### ISSUE TITLE
Title: Gym Website

### ISSUE THREAD

**Issue by sanskarmalkhede** [RajVarsani/html-archives#82]
### Describe your issue.

I have a made a Gym website which I would like to add in your repo.

### Screenshots (if applicable).

![image](https://user-images.githubusercontent.com/85408959/194749632-6e81c385-1189-4419-8d69-1ca30f778a52.png)

**Comment by RajVarsani** [comment]
Sure LGTM, Go ahead @sanskarmalkhede

**Comment by sanskarmalkhede** [comment]
done 👍🏻
