### ISSUE TITLE
Title: Embark- College Guide

### ISSUE THREAD

**Issue by Nitya-Pasrija** [RajVarsani/html-archives#89]
### Describe your issue.

I wish to add a Website project using HTML and CSS, that will be helpful for college students and be a guide to them.

### Screenshots (if applicable).

![image](https://user-images.githubusercontent.com/97171261/194762055-20d0a842-2c3f-48e3-8d58-fe7615f55c5b.png)
![image](https://user-images.githubusercontent.com/97171261/194762081-ac41c5d6-214d-4a5f-9a64-709964afcaf4.png)
![image](https://user-images.githubusercontent.com/97171261/194762108-a8868696-a272-4713-94cf-d09797a5f182.png)

### Additional context (if any)

This webpage links up different blog sites and roadmaps, to help guide better

**Comment by RajVarsani** [comment]
Nice initiative 🙌
Sure, Go ahead @Nitya-Pasrija
